general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    path = /home/matyas/wallpapers/wallhaven-je17z5.png
    blur_passes = 3
    blur_size = 2
    brightness = 0.6
}

# Greeting
label {
    monitor =
    text = cmd[update:0] echo "Hi, $USER"
    color = rgba(255, 255, 255, 0.6)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, 320
    halign = center
    valign = center
}

# Hours
label {
    monitor =
    text = cmd[update:1000] date +"%H"
    color = rgba(255, 255, 255, 0.92)
    font_size = 112
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 220
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 4
    shadow_color = rgba(00000099)
}

# Minutes
label {
    monitor =
    text = cmd[update:1000] date +"%M"
    color = rgba(255, 255, 255, 0.92)
    font_size = 112
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 80
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 4
    shadow_color = rgba(00000099)
}

# Day name
label {
    monitor =
    text = cmd[update:18000000] date +'%A'
    color = rgba(255, 255, 255, 0.55)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, -15
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:18000000] date +'%d %b'
    color = rgba(255, 255, 255, 0.45)
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 0, -40
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.26
    dots_spacing = 0.64
    dots_center = true
    rounding = 22
    outer_color = rgba(255, 255, 255, 0.3)
    inner_color = rgba(0, 0, 0, 0.4)
    font_color = rgba(255, 255, 255, 0.85)
    fade_on_empty = true
    placeholder_text = <i>  Password...</i>
    font_family = JetBrainsMono Nerd Font
    position = 0, 120
    halign = center
    valign = bottom
    check_color = rgba(100, 220, 100, 0.85)
    fail_color = rgba(255, 85, 85, 0.85)
}
